services:
  api:
    platform: linux/amd64
    image: sjc.vultrcr.com/frankistry/automate/api:${APP_VERSION:-local}
    build:
      context: .
      target: final
    ports:
      - "8080"
    scale: 1
    depends_on:
      - postgres

  api-debug:
    platform: linux/amd64
    image: automate.api-debug
    build:
      context: .
      target: debug
    entrypoint: [dotnet, watch, run]
    depends_on:
      - postgres
    volumes:
      - ./AutoMate:/source/AutoMate

  api-functional-tests:
    platform: linux/amd64
    image: alpine/httpie
    restart: unless-stopped
    entrypoint: [/tests/functional.sh, http://api-debug:8080]
    depends_on:
      - api-debug
    volumes:
      - ./tests:/tests

  api-unit-tests:
    platform: linux/amd64
    image: automate.api-unit-tests
    build:
      context: .
      target: unit-test
    entrypoint: [dotnet, watch, test]
    volumes:
      - ./AutoMate:/source/AutoMate
      - ./AutoMate.Tests:/source/AutoMate.Tests

  postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
