name: Build

on:
  workflow_call:
    inputs:
      app_version:
        default: latest-build
        required: false
        type: string
      registry:
        default: sjc.vultrcr.com/frankistry
        required: false
        type: string

jobs:
  build-fsharp-api-automate:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
      REGISTRY: ${{ inputs.registry }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker images
        working-directory: fsharp/api/automate
        run: docker compose build
