name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    uses: ./.github/workflows/build.yaml

  secrets:
    runs-on: ubuntu-latest
    steps:
      - id: op-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          VULTR_API_KEY: op://Frankenstructure/Vultr API Key/password
      - uses: defrank/action-vultr@v2024.10.20-1
        with:
          token: ${{ steps.op-secrets.outputs.VULTR_API_KEY }}
      - id: vultr-secrets
        env:
          VULTR_API_KEY: ${{ steps.op-secrets.outputs.VULTR_API_KEY }}
        run: >
          vultr-cli --output=json object-storage list
          | jq --raw-output >> "$GITHUB_OUTPUT" '
          .object_storages[]
          | select(.label == "frankenstorage")
          | ["S3_ACCESS_KEY=" + .s3_access_key, "S3_SECRET_KEY=" + .s3_secret_key]
          | join("\n")
          '

          echo -n "KUBECONFIG_BASE64=" >> "$GITHUB_OUTPUT";
          vultr-cli --output=json kubernetes list
          | jq --raw-output '.vke_clusters[] | select(.label == "frank8s").id'
          | xargs -- vultr-cli kubernetes config >> "$GITHUB_OUTPUT"
    outputs:
      S3_ACCESS_KEY: ${{ steps.vultr-secrets.outputs.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ steps.vultr-secrets.outputs.S3_SECRET_KEY }}
      KUBECONFIG_BASE64: ${{ steps.vultr-secrets.outputs.KUBECONFIG_BASE64 }}
      VULTR_API_KEY: ${{ steps.op-secrets.outputs.VULTR_API_KEY }}

  deploy-prod-frankenstructure:
    environment: production
    needs:
      - lint
      - secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opentofu/setup-opentofu@v1
      - name: Initialize tofu
        working-directory: terraform/infrastructure/frankenstructure
        run: tofu init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_vultr_api_key: ${{ needs.secrets.outputs.VULTR_API_KEY }}
      - name: Deploy frankenstructure
        working-directory: terraform/infrastructure/frankenstructure
        run: tofu apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_vultr_api_key: ${{ needs.secrets.outputs.VULTR_API_KEY }}

  deploy-prod-n8n:
    environment: production
    needs:
      - lint
      - secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opentofu/setup-opentofu@v1
      - id: secrets
        run: |
          base64 --decode > "kubeconfig.yaml" <<< "${{ needs.secrets.outputs.KUBECONFIG_BASE64 }}"
          echo "KUBECONFIG_PATH=$PWD/kubeconfig.yaml" >> "$GITHUB_OUTPUT"
      - name: Initialize tofu
        working-directory: terraform/applications/n8n
        run: tofu init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_kubeconfig: ${{ steps.secrets.outputs.KUBECONFIG_PATH }}
      - name: Deploy n8n
        working-directory: terraform/applications/n8n
        run: tofu apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_kubeconfig: ${{ steps.secrets.outputs.KUBECONFIG_PATH }}

  deploy-prod-node-red:
    environment: production
    needs:
      - lint
      - secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opentofu/setup-opentofu@v1
      - id: secrets
        run: |
          base64 --decode > "kubeconfig.yaml" <<< "${{ needs.secrets.outputs.KUBECONFIG_BASE64 }}"
          echo "KUBECONFIG_PATH=$PWD/kubeconfig.yaml" >> "$GITHUB_OUTPUT"
      - name: Initialize tofu
        working-directory: terraform/applications/node-red
        run: tofu init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_kubeconfig: ${{ steps.secrets.outputs.KUBECONFIG_PATH }}
          TF_VAR_github_username: ${{ github.triggering_actor }}
          TF_VAR_github_token: ${{ github.token }}
      - name: Deploy Node-RED
        working-directory: terraform/applications/node-red
        run: tofu apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.secrets.outputs.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.secrets.outputs.S3_SECRET_KEY }}
          TF_VAR_kubeconfig: ${{ steps.secrets.outputs.KUBECONFIG_PATH }}
          TF_VAR_github_username: ${{ github.triggering_actor }}
          TF_VAR_github_token: ${{ github.token }}
