name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  fsharp-api-AutoMate-build:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: 0.1.0
      REGISTRY: sjc.vultrcr.com/frankistry
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker images
        working-directory: fsharp/api/AutoMate
        run: docker compose build
